GG.codeNameGenerator =

  generate: ->
    rand = (arr) ->
      word = arr[Math.floor(Math.random() * arr.length)]
      word[0].toUpperCase() + word[1..-1].toLowerCase()
    rand(@firstName) + rand(@lastName)

  firstName: [
    "adventurous"
    "amiable"
    "amicable"
    "amusing"
    "brave"
    "bright"
    "calm"
    "careful"
    "charming"
    "conscientious"
    "considerate"
    "courageous"
    "courteous"
    "creative"
    "decisive"
    "determined"
    "dynamic"
    "easygoing"
    "emotional"
    "energetic"
    "enthusiastic"
    "exuberant"
    "faithful"
    "fearless"
    "forceful"
    "frank"
    "friendly"
    "funny"
    "generous"
    "gentle"
    "good"
    "gregarious"
    "helpful"
    "honest"
    "humorous"
    "imaginative"
    "independent"
    "intellectual"
    "intelligent"
    "intuitive"
    "inventive"
    "kind"
    "loyal"
    "patient"
    "persistent"
    "pioneering"
    "placid"
    "plucky"
    "powerful"
    "practical"
    "quiet"
    "reliable"
    "reserved"
    "resourceful"
    "romantic"
    "sensible"
    "sensitive"
    "shy"
    "sincere"
    "sociable"
    "thoughtful"
    "tidy"
    "tough"
    "versatile"
    "willing"
    "witty"
  ],

  lastName: [
    "adventurer"
    "dragonbreeder"
    "dragonfriend"
    "dragonrider"
    "dragonseeker"
    "dragonwhisperer"
    "wanderer"
  ]
